### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

### ISSUE THREAD

**Issue by PaPaPaulitos** [PaPaPaulitos/sherlock-lib#1]
## Python Infos

- System: Windows 10
- Python Version: 3.12.1

## Description

This error should have a message like this:

```bash
Traceback (most recent call last):
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\main.py", line 1, in <module>
    from sherlock_lib import search_target
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\sherlock_lib\__init__.py", line 7, in <module>
    from .controllers import search_target
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\sherlock_lib\controllers\__init__.py", line 1, in <module>
    from .sherlock_get_response import get_response
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\sherlock_lib\controllers\sherlock_get_response.py", line 1, in <module>
    import requests
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\urllib3\__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "C:\Users\Hammy\Desktop\Nova pasta (2)\venv\Lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

## Fix

- Install urllib3 in version urllib3=1.26.13

```bash
pip install urllib3==1.26.13
```

- An error message like this should appear, but don't worry, it means that the lib is working.

```bash
\venv\Lib\site-packages\requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
````

**Comment by PaPaPaulitos** [comment]
I believe that this resolution works for all operating systems.
